/*
ARDUINO BASED GYROSCOPE CONTROLLED ROBOT BY TEAM FROM FACULTY OF ENGINEERING FROM ELECTRICAL DEPARTMENT 
NAMES:
SANDRA ESSAM YOUSSEF
NADA MOHAMED ALI
ISRAA MAMDOUH
MERNA NESSEM THABET.
THIS PROJECT WILL HELP YOU TO UNDERSTAND THE ARDUINO MICROCONTROLLER
, MOTOR DRIVER MODULE AND GY-521 GYROSCOPE MODULE IN AN EASY WAY.IT CONSIST OF THREE CODES
ONE FOR THE AT COMMANDS, THE SECOND FOR THE TRANSMITTER, THE LAST FOR THE RECIEVER
WORKING OF THIS PROJECT :-
THE GYROSCOPE SENSOR IS ALSO KNOWN AS THE TILT SENSOR. IT SENSES ITS 
MOVEMENTS AND PROVIDES THE VALUES TO THE ARDUINO. THE GYROSCOPE MODULE 
WORKS ON ALL THE THREE AXIS NAMELY THE X,Y AND Z. WHEN THE ARDUINO RECEIVES 
THESE VALUES IT USES THEM WITH THE IF ELSE STATEMENTS TO DRIVE THE MOTORS ACCORDINGLY.
THE CONNECTIONS BETWWEN THE GYROSCOPE MODULE AND THE ARDUINO ARE GIVEN BELOW. 
GYRO<<ARDUINO
VCC<<VCC
GND<<GND
SCL<<A5
SDA<<A4
AD0<<GND
INT<<D2*/
//  هدا الكود يستخدم لتعريف البلوتوث كMASTER OR SLAVE باستخدام الAT COMMANDS
#include <SoftwareSerial.h>

SoftwareSerial BTSerial(10, 11); // RX | TX

void setup()
{
  pinMode(9, OUTPUT);  // this pin will pull the HC-05 pin 34 (key pin) HIGH to switch module to AT mode
  digitalWrite(9, HIGH);
  Serial.begin(9600);
  Serial.println("Enter AT commands:");
  BTSerial.begin(38400);  // HC-05 default speed in AT command more
}

void loop()
{

  // Keep reading from HC-05 and send to Arduino Serial Monitor
  if (BTSerial.available())
    Serial.write(BTSerial.read());

  // Keep reading from Arduino Serial Monitor and send to HC-05
  if (Serial.available())
    BTSerial.write(Serial.read());
}
